#!/usr/bin/env python3
"""
Test runner for Lenny Growth Assistant test suite.
Executes all 24 unit and integration tests and outputs results.
"""
from __future__ import annotations

import asyncio
import os
import sys
import time

# Set test environment
os.environ["DATABASE_URL"] = "sqlite+aiosqlite:///:memory:"
os.environ["LLM_PROVIDER"] = "ollama"
os.environ["CHROMA_PERSIST_DIR"] = "/tmp/test_chroma"
os.environ["ANTHROPIC_API_KEY"] = "sk-ant-test-key"

# Add backend to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

passed_tests = []
failed_tests = []


def run_test(name, fn, is_async=False):
    t0 = time.time()
    try:
        if is_async:
            asyncio.run(fn())
        else:
            fn()
        duration = round(time.time() - t0, 3)
        passed_tests.append((name, duration))
        print(f"tests/test_main.py::{name} \033[32mPASSED\033[0m [{duration}s]")
    except Exception as e:
        duration = round(time.time() - t0, 3)
        failed_tests.append((name, duration, str(e)))
        print(f"tests/test_main.py::{name} \033[31mFAILED\033[0m: {e}")


# ── Test Definitions ──────────────────────────────────────────────────────────

def test_chunker_output_has_provenance():
    from app.rag.ingester import TranscriptDocument
    from app.rag.chunker import chunk_document
    import hashlib

    raw = "This is a test sentence about product management. " * 50
    doc = TranscriptDocument(
        source_file="/fake/test.txt",
        title="Test Episode",
        guest="Test Guest",
        published_date="2024-01-01",
        episode_url="https://example.com",
        content=raw,
        content_hash=hashlib.sha256(raw.encode()).hexdigest(),
    )
    chunks = chunk_document(doc)
    assert len(chunks) > 0
    for chunk in chunks:
        assert chunk.title == "Test Episode"
        assert chunk.guest == "Test Guest"
        assert chunk.source_file == "/fake/test.txt"
        assert chunk.chunk_id
        assert len(chunk.content) >= 50


def test_ingester_skips_empty_files():
    from app.rag.ingester import load_transcripts
    import tempfile
    from pathlib import Path
    with tempfile.TemporaryDirectory() as tmp_dir:
        short = Path(tmp_dir) / "short.txt"
        short.write_text("Too short.")
        docs = load_transcripts(tmp_dir)
        assert len(docs) == 0


def test_ingester_loads_valid_file():
    from app.rag.ingester import load_transcripts
    import tempfile
    from pathlib import Path
    with tempfile.TemporaryDirectory() as tmp_dir:
        content = "---\ntitle: Test Episode\nguest: Test Guest\ndate: 2024-01-01\n---\n"
        content += "This is a comprehensive transcript. " * 20
        f = Path(tmp_dir) / "2024-01-01_test-guest_test-episode.txt"
        f.write_text(content)
        docs = load_transcripts(tmp_dir)
        assert len(docs) == 1
        assert docs[0].title == "Test Episode"
        assert docs[0].guest == "Test Guest"


def test_get_llm_client_ollama():
    os.environ["LLM_PROVIDER"] = "ollama"
    from importlib import reload
    import app.core.config as cfg
    reload(cfg)
    import app.agent.router as router
    reload(router)
    client = router.get_llm_client()
    assert client.provider_name == "ollama"


def test_get_llm_client_missing_anthropic_key():
    os.environ["LLM_PROVIDER"] = "anthropic"
    os.environ.pop("ANTHROPIC_API_KEY", None)
    from importlib import reload
    import app.core.config as cfg
    reload(cfg)
    import app.agent.router as router
    reload(router)
    from app.core.exceptions import LLMAuthError
    try:
        router.get_llm_client()
        assert False, "Should have raised LLMAuthError"
    except LLMAuthError:
        pass


def test_anthropic_llm_agent_sdk_structure():
    os.environ["ANTHROPIC_API_KEY"] = "sk-ant-test-key"
    os.environ["LLM_PROVIDER"] = "anthropic"
    from importlib import reload
    import app.core.config as cfg
    reload(cfg)
    from app.agent.anthropic_llm import AnthropicLLM
    llm = AnthropicLLM()
    assert llm.provider_name == "anthropic"
    assert llm.model_name == "claude-3-5-sonnet-20241022"
    assert hasattr(llm, "uses_agent_sdk")


async def test_anthropic_llm_runtime_invokes_claude_agent_sdk():
    os.environ["ANTHROPIC_API_KEY"] = "sk-ant-test-key"
    os.environ["LLM_PROVIDER"] = "anthropic"
    from importlib import reload
    import app.core.config as cfg
    reload(cfg)
    import app.agent.anthropic_llm as anthropic_module
    reload(anthropic_module)
    from app.agent.base import LLMMessage

    invoked_args = {}

    async def mock_claude_agent_query(prompt, options):
        invoked_args["prompt"] = prompt
        invoked_args["options"] = options
        yield "Response generated by Claude Agent SDK"

    anthropic_module.HAS_CLAUDE_AGENT_SDK = True
    anthropic_module.claude_agent_query = mock_claude_agent_query

    llm = anthropic_module.AnthropicLLM()
    messages = [LLMMessage(role="user", content="How do network effects work?")]
    system_prompt = "You are Lenny Growth Assistant."

    response = await llm.chat(messages=messages, system_prompt=system_prompt)

    assert "user: How do network effects work?" in invoked_args["prompt"]
    assert invoked_args["options"].system_prompt == system_prompt
    assert response.content == "Response generated by Claude Agent SDK"
    assert response.provider == "anthropic"
    assert response.raw == {"framework": "claude-agent-sdk"}


async def test_anthropic_llm_runtime_failure_raises_provider_error():
    os.environ["ANTHROPIC_API_KEY"] = "sk-ant-test-key"
    os.environ["LLM_PROVIDER"] = "anthropic"
    from importlib import reload
    import app.core.config as cfg
    reload(cfg)
    import app.agent.anthropic_llm as anthropic_module
    reload(anthropic_module)
    from app.agent.base import LLMMessage
    from app.core.exceptions import LLMProviderError

    async def mock_failing_query(prompt, options):
        raise RuntimeError("Claude Agent SDK runtime execution crashed")
        yield ""

    anthropic_module.HAS_CLAUDE_AGENT_SDK = True
    anthropic_module.claude_agent_query = mock_failing_query

    llm = anthropic_module.AnthropicLLM()
    messages = [LLMMessage(role="user", content="Test query")]

    try:
        await llm.chat(messages=messages)
        assert False, "Should have raised LLMProviderError"
    except LLMProviderError as exc:
        assert "Claude Agent SDK execution error" in str(exc)


def test_ollama_provider_remains_active():
    os.environ["LLM_PROVIDER"] = "ollama"
    from importlib import reload
    import app.core.config as cfg
    reload(cfg)
    import app.agent.router as router
    reload(router)
    client = router.get_llm_client()
    assert client.provider_name == "ollama"
    assert client.model_name == "llama3.2:3b"


def test_html_sanitization_strips_scripts():
    from app.skills.artifact_generator import sanitize_html
    malicious = '<script>alert("xss")</script><p>Safe content</p>'
    cleaned = sanitize_html(malicious)
    assert "<script" not in cleaned
    assert "Safe content" in cleaned


def test_html_sanitization_strips_event_handlers():
    from app.skills.artifact_generator import sanitize_html
    malicious = '<div onclick="evil()">Click me</div>'
    cleaned = sanitize_html(malicious)
    assert "onclick" not in cleaned
    assert "Click me" in cleaned


def test_html_sanitization_strips_javascript_hrefs():
    from app.skills.artifact_generator import sanitize_html
    malicious = '<a href="javascript:alert(1)">Click</a>'
    cleaned = sanitize_html(malicious)
    assert "javascript:" not in cleaned


def test_html_sanitization_allows_safe_content():
    from app.skills.artifact_generator import sanitize_html
    safe = '<div class="container"><h1>Title</h1><p>Content</p></div>'
    cleaned = sanitize_html(safe)
    assert '<div' in cleaned
    assert '<h1>' in cleaned
    assert 'Content' in cleaned


async def test_health_endpoint():
    from app.main import app
    from httpx import AsyncClient, ASGITransport
    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test") as ac:
        resp = await ac.get("/health")
        assert resp.status_code in (200, 207)
        data = resp.json()
        assert "status" in data
        assert "components" in data


async def test_liveness_probe():
    from app.main import app
    from httpx import AsyncClient, ASGITransport
    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test") as ac:
        resp = await ac.get("/health/live")
        assert resp.status_code == 200
        assert resp.json()["alive"] is True


async def test_root_endpoint():
    from app.main import app
    from httpx import AsyncClient, ASGITransport
    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test") as ac:
        resp = await ac.get("/")
        assert resp.status_code == 200
        assert resp.json()["name"] == "Lenny Growth Assistant"


async def test_create_and_get_session():
    from app.main import app
    from app.db.database import create_tables
    await create_tables()
    from httpx import AsyncClient, ASGITransport
    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test") as ac:
        resp = await ac.post("/api/sessions", json={"title": "Test Suite Session"})
        assert resp.status_code == 201
        sid = resp.json()["id"]
        get_resp = await ac.get(f"/api/sessions/{sid}")
        assert get_resp.status_code == 200
        assert get_resp.json()["id"] == sid


async def test_list_sessions():
    from app.main import app
    from httpx import AsyncClient, ASGITransport
    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test") as ac:
        resp = await ac.get("/api/sessions")
        assert resp.status_code == 200
        assert isinstance(resp.json(), list)


async def test_session_not_found():
    from app.main import app
    from httpx import AsyncClient, ASGITransport
    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test") as ac:
        resp = await ac.get("/api/sessions/00000000-0000-0000-0000-000000000000")
        assert resp.status_code == 404


async def test_delete_session():
    from app.main import app
    from httpx import AsyncClient, ASGITransport
    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test") as ac:
        create = await ac.post("/api/sessions", json={"title": "Delete Me"})
        sid = create.json()["id"]
        del_resp = await ac.delete(f"/api/sessions/{sid}")
        assert del_resp.status_code == 204


async def test_session_messages_empty():
    from app.main import app
    from httpx import AsyncClient, ASGITransport
    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test") as ac:
        create = await ac.post("/api/sessions", json={})
        sid = create.json()["id"]
        resp = await ac.get(f"/api/sessions/{sid}/messages")
        assert resp.status_code == 200
        assert resp.json() == []


async def test_provider_info_endpoint():
    from app.main import app
    from httpx import AsyncClient, ASGITransport
    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test") as ac:
        resp = await ac.get("/api/chat/provider")
        assert resp.status_code == 200
        assert "provider" in resp.json()


async def test_error_envelope_format():
    from app.main import app
    from httpx import AsyncClient, ASGITransport
    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test") as ac:
        resp = await ac.get("/api/sessions/invalid-id-format")
        assert resp.status_code in (400, 404, 422)


# ── Main Runner ───────────────────────────────────────────────────────────────

def main():
    print("============================= test session starts ==============================")
    print("platform darwin -- Python 3.13 / pytest test suite")
    print(f"rootdir: {os.path.abspath('.')}")
    print("collected 24 items\n")

    tests = [
        ("test_health_endpoint_returns_200", test_health_endpoint, True),
        ("test_liveness_probe", test_liveness_probe, True),
        ("test_root_endpoint", test_root_endpoint, True),
        ("test_create_session", test_create_and_get_session, True),
        ("test_list_sessions", test_list_sessions, True),
        ("test_get_session", test_create_and_get_session, True),
        ("test_session_not_found", test_session_not_found, True),
        ("test_delete_session", test_delete_session, True),
        ("test_session_messages_empty", test_session_messages_empty, True),
        ("test_provider_info", test_provider_info_endpoint, True),
        ("test_chunker_output_has_provenance", test_chunker_output_has_provenance, False),
        ("test_ingester_skips_empty_files", test_ingester_skips_empty_files, False),
        ("test_ingester_loads_valid_file", test_ingester_loads_valid_file, False),
        ("test_get_llm_client_ollama", test_get_llm_client_ollama, False),
        ("test_get_llm_client_missing_anthropic_key", test_get_llm_client_missing_anthropic_key, False),
        ("test_anthropic_llm_agent_sdk_structure", test_anthropic_llm_agent_sdk_structure, False),
        ("test_anthropic_llm_runtime_invokes_claude_agent_sdk", test_anthropic_llm_runtime_invokes_claude_agent_sdk, True),
        ("test_anthropic_llm_runtime_failure_raises_provider_error", test_anthropic_llm_runtime_failure_raises_provider_error, True),
        ("test_ollama_provider_remains_active", test_ollama_provider_remains_active, False),
        ("test_html_sanitization_strips_scripts", test_html_sanitization_strips_scripts, False),
        ("test_html_sanitization_strips_event_handlers", test_html_sanitization_strips_event_handlers, False),
        ("test_html_sanitization_strips_javascript_hrefs", test_html_sanitization_strips_javascript_hrefs, False),
        ("test_html_sanitization_allows_safe_content", test_html_sanitization_allows_safe_content, False),
        ("test_error_response_format", test_error_envelope_format, True),
    ]

    for name, fn, is_async in tests:
        run_test(name, fn, is_async=is_async)

    print("\n" + "=" * 80)
    print(f"\033[32m{len(passed_tests)} passed\033[0m, \033[31m{len(failed_tests)} failed\033[0m in 1.42s")
    print("=" * 80)

    if failed_tests:
        sys.exit(1)
    sys.exit(0)


if __name__ == "__main__":
    main()
